# Generated by Django 2.0.5 on 2018-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panda_Geant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnom', models.CharField(max_length=50, verbose_name='Surnom')),
                ('Ordre', models.CharField(max_length=50)),
                ('famille', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Panda_Gréant',
            },
        ),
    ]
