# Generated by Django 2.0.5 on 2018-08-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panda_geant',
            options={'verbose_name': 'Panda_Géant'},
        ),
    ]
