# Generated by Django 2.0.5 on 2018-08-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wok', '0002_auto_20180828_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panda_geant',
            old_name='Ordre',
            new_name='ordre',
        ),
    ]
